In [1]:

from tensorflow.keras.preprocessing.text import one_hot


In [2]:
## Sentences
sent=['the glass of milk',
      'the glass of juice',
      'the cup of tea',
      'I am agood boy',
      'I am a good developer',
      'Understand the meaning of words',
      'your videos are good']

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am agood boy',
 'I am a good developer',
 'Understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
## One hot Representation
one_hot_repr=[one_hot(words,voc_size) for words in sent]

In [6]:
one_hot_repr

[[2238, 8071, 570, 8839],
 [2238, 8071, 570, 3315],
 [2238, 4116, 570, 2584],
 [5847, 8583, 2381, 4205],
 [5847, 8583, 7997, 7737, 2219],
 [807, 2238, 6257, 570, 9382],
 [1644, 1372, 8409, 7737]]

In [7]:
# Word Embedding Representation
from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential


In [8]:

import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2238 8071  570 8839]
 [   0    0    0    0 2238 8071  570 3315]
 [   0    0    0    0 2238 4116  570 2584]
 [   0    0    0    0 5847 8583 2381 4205]
 [   0    0    0 5847 8583 7997 7737 2219]
 [   0    0    0  807 2238 6257  570 9382]
 [   0    0    0    0 1644 1372 8409 7737]]


In [10]:
# feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(input_dim=voc_size,output_dim=dim))
model.build(input_shape=(None,8))
model.compile('adam','mse')


In [12]:

print(model.summary())

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

None


In [13]:
print(model.predict(embedded_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 315ms/step
[[[-0.0177261   0.0421319   0.04327599 -0.00900668  0.0015376
    0.03199642  0.01091374  0.01111985 -0.03171009  0.03825415]
  [-0.0177261   0.0421319   0.04327599 -0.00900668  0.0015376
    0.03199642  0.01091374  0.01111985 -0.03171009  0.03825415]
  [-0.0177261   0.0421319   0.04327599 -0.00900668  0.0015376
    0.03199642  0.01091374  0.01111985 -0.03171009  0.03825415]
  [-0.0177261   0.0421319   0.04327599 -0.00900668  0.0015376
    0.03199642  0.01091374  0.01111985 -0.03171009  0.03825415]
  [-0.0060001   0.0193587  -0.04735109  0.00255946  0.00338123
   -0.02711232 -0.00974172 -0.02723275  0.0182858   0.00025547]
  [-0.03162064 -0.00522482 -0.02182552 -0.02781698 -0.00489192
   -0.02932186 -0.04671221  0.00184076  0.01539152 -0.00561774]
  [-0.03240341  0.00300549  0.02671641  0.00834106 -0.00779665
   -0.03746698 -0.00921782 -0.02178812 -0.04321757  0.04958853]
  [ 0.02869464 -0.04030753  0.02710891 -0.03064911  0.04557754
    0.0074909

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 2238, 8071,  570, 8839])

In [15]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step


array([[[-0.0177261 ,  0.0421319 ,  0.04327599, -0.00900668,
          0.0015376 ,  0.03199642,  0.01091374,  0.01111985,
         -0.03171009,  0.03825415],
        [-0.0177261 ,  0.0421319 ,  0.04327599, -0.00900668,
          0.0015376 ,  0.03199642,  0.01091374,  0.01111985,
         -0.03171009,  0.03825415],
        [-0.0177261 ,  0.0421319 ,  0.04327599, -0.00900668,
          0.0015376 ,  0.03199642,  0.01091374,  0.01111985,
         -0.03171009,  0.03825415],
        [-0.0177261 ,  0.0421319 ,  0.04327599, -0.00900668,
          0.0015376 ,  0.03199642,  0.01091374,  0.01111985,
         -0.03171009,  0.03825415],
        [-0.0060001 ,  0.0193587 , -0.04735109,  0.00255946,
          0.00338123, -0.02711232, -0.00974172, -0.02723275,
          0.0182858 ,  0.00025547],
        [-0.03162064, -0.00522482, -0.02182552, -0.02781698,
         -0.00489192, -0.02932186, -0.04671221,  0.00184076,
          0.01539152, -0.00561774],
        [-0.03240341,  0.00300549,  0.02671641,  0.0